import { NextRequest } from "next/server";
import type { DetectedGap } from "@/lib/gapAI/detectGaps";

export async function POST(req: NextRequest) {
  const { gaps, query } = await req.json() as { gaps: DetectedGap[]; query: string };

  const gapsHtml = gaps.map((gap, i) => `
    <div style="page-break-inside:avoid;margin-bottom:32px;padding:24px;border:1px solid #e5e7eb;border-radius:8px;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
        <span style="font-size:12px;font-weight:600;padding:2px 8px;border-radius:999px;background:#f3f4f6;color:#6b7280;">#${i+1}</span>
        <span style="font-size:12px;color:#7c3aed;font-weight:500;">${gap.category.replace(/-/g," ")}</span>
        <span style="font-size:12px;color:#6b7280;margin-left:auto;">Score: ${gap.relevanceScore * 10}/100</span>
      </div>
      <h3 style="font-size:18px;font-weight:700;color:#111827;margin:0 0 12px;">${gap.title}</h3>
      <p style="color:#4b5563;line-height:1.6;margin-bottom:16px;">${gap.description}</p>
      ${gap.whatsMissing ? `<div style="margin-bottom:12px;"><strong style="font-size:11px;text-transform:uppercase;color:#9ca3af;">What's Missing</strong><p style="color:#4b5563;margin-top:4px;">${gap.whatsMissing}</p></div>` : ""}
      ${gap.whyItMatters ? `<div style="margin-bottom:12px;"><strong style="font-size:11px;text-transform:uppercase;color:#9ca3af;">Why It Matters</strong><p style="color:#4b5563;margin-top:4px;">${gap.whyItMatters}</p></div>` : ""}
      ${gap.whyUnresolved ? `<div style="margin-bottom:12px;"><strong style="font-size:11px;text-transform:uppercase;color:#9ca3af;">Why It's Unresolved</strong><p style="color:#4b5563;margin-top:4px;">${gap.whyUnresolved}</p></div>` : ""}
      ${gap.suggestedDirection ? `<div style="padding:12px;background:#f5f3ff;border-left:3px solid #7c3aed;border-radius:4px;margin-bottom:12px;"><strong style="font-size:11px;text-transform:uppercase;color:#7c3aed;">Suggested Direction</strong><p style="color:#5b21b6;font-weight:500;margin-top:4px;">${gap.suggestedDirection}</p></div>` : ""}
      ${gap.citations.length > 0 ? `<div><strong style="font-size:11px;text-transform:uppercase;color:#9ca3af;">Supporting Literature</strong><ul style="margin-top:8px;padding-left:16px;">${gap.citations.map((c,ci) => `<li style="color:#4b5563;margin-bottom:4px;font-size:13px;">[${ci+1}] ${c.title} — ${c.authors.slice(0,2).join(", ")}${c.authors.length>2?" et al.":""} (${c.year??"n.d."}) <a href="${c.url}" style="color:#7c3aed;">[link]</a></li>`).join("")}</ul></div>` : ""}
    </div>`).join("");

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>GapForge Report</title>
<style>body{font-family:-apple-system,sans-serif;max-width:800px;margin:0 auto;padding:40px 20px;color:#111827;}@media print{body{padding:0;}}</style>
</head><body>
<div style="display:flex;align-items:center;gap:12px;margin-bottom:8px;">
  <div style="width:32px;height:32px;background:#7c3aed;border-radius:8px;display:flex;align-items:center;justify-content:center;"><span style="color:white;font-weight:900;font-size:16px;">G</span></div>
  <span style="font-weight:800;font-size:20px;color:#7c3aed;">GapForge</span>
</div>
<h1 style="font-size:28px;font-weight:800;margin-bottom:4px;">Research Gap Report</h1>
<p style="color:#6b7280;font-size:14px;margin-bottom:32px;">Query: "${query}" &nbsp;·&nbsp; ${gaps.length} gap${gaps.length!==1?"s":""} found &nbsp;·&nbsp; ${new Date().toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})}</p>
${gapsHtml}
<div style="margin-top:40px;padding-top:20px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;text-align:center;">Generated by GapForge — gapforge.app</div>
</body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="gapforge-report-${Date.now()}.html"`,
    },
  });
}
