"use client";

import { useState, useEffect } from "react";
import { AppNav } from "@/components/nav";
import { motion } from "framer-motion";
import {
  FileText, Download, Share2, Copy, Check, Loader2,
  Zap, BookOpen, Trophy, Flame, Star, Clock, User, Building2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useSession } from "next-auth/react";

interface CVData {
  name: string;
  email: string;
  institution: string;
  bio: string;
  careerStage: string;
  researchAreas: string[];
  stats: {
    gapsFound: number;
    papersSaved: number;
    searchesRun: number;
    streak: number;
    proposalsDrafted: number;
  };
  badges: { badge_type: string; earned_at: string }[];
  recentGaps: { title: string; category: string; created_at: string }[];
  keywords: string[];
}

const BADGE_LABELS: Record<string, string> = {
  "first-gap": "First Gap Discovered",
  "gap-hunter-10": "Gap Hunter (10+ gaps)",
  "week-streak": "7-Day Research Streak",
  "prolific-10": "Prolific Researcher",
  "collaborator": "Active Collaborator",
};

export default function ResearchCVPage() {
  const { data: session } = useSession();
  const [cvData, setCvData] = useState<CVData | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    Promise.all([
      fetch("/api/portfolio").then(r => r.json()),
      fetch("/api/credits").then(r => r.json()),
      fetch("/api/user/streak").then(r => r.json()),
      fetch("/api/gap-ai/save").then(r => r.json()),
    ]).then(([portfolio, credits, streakData, saved]) => {
      setCvData({
        name: session?.user?.name ?? portfolio.name ?? "Researcher",
        email: session?.user?.email ?? "",
        institution: portfolio.institution ?? "",
        bio: portfolio.bio ?? "",
        careerStage: portfolio.career_stage ?? "",
        researchAreas: portfolio.research_areas ?? [],
        keywords: portfolio.keywords ?? [],
        stats: {
          gapsFound: portfolio.gap_count ?? 0,
          papersSaved: (saved.saved ?? []).length,
          searchesRun: credits.creditsUsed ?? 0,
          streak: streakData.streak ?? 0,
          proposalsDrafted: 0,
        },
        badges: portfolio.badges ?? [],
        recentGaps: (portfolio.recent_gaps ?? []).slice(0, 5),
      });
    }).catch(() => {}).finally(() => setLoading(false));
  }, [session]);

  const exportMarkdown = () => {
    if (!cvData) return;
    const md = `# ${cvData.name} — Research CV
${cvData.institution ? `**${cvData.institution}**` : ""}${cvData.careerStage ? ` · ${cvData.careerStage}` : ""}
${cvData.email}

## Research Profile
${cvData.bio || "Researcher on GapForge."}

${cvData.researchAreas.length > 0 ? `**Research Areas:** ${cvData.researchAreas.join(", ")}` : ""}
${cvData.keywords.length > 0 ? `**Keywords:** ${cvData.keywords.join(", ")}` : ""}

## GapForge Research Activity
- Research gaps discovered: **${cvData.stats.gapsFound}**
- Academic papers analyzed: **${cvData.stats.papersSaved}**
- Gap AI searches run: **${cvData.stats.searchesRun}**
- Current research streak: **${cvData.stats.streak} days**

${cvData.recentGaps.length > 0 ? `## Recently Discovered Gaps\n${cvData.recentGaps.map((g, i) => `${i + 1}. ${g.title} *(${g.category.replace(/-/g, " ")})*`).join("\n")}` : ""}

${cvData.badges.length > 0 ? `## Achievements\n${cvData.badges.map(b => `- ${BADGE_LABELS[b.badge_type] ?? b.badge_type}`).join("\n")}` : ""}

---
*Generated by GapForge — gapforge-self.vercel.app*`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = `${cvData.name.replace(/\s/g, "-")}-research-cv.md`; a.click();
    URL.revokeObjectURL(url);
  };

  const copyText = () => {
    if (!cvData) return;
    navigator.clipboard.writeText(`${cvData.name} | Research Profile\nGaps found: ${cvData.stats.gapsFound} | Searches: ${cvData.stats.searchesRun} | Streak: ${cvData.stats.streak} days\nResearch areas: ${cvData.researchAreas.join(", ")}\nView full profile: gapforge-self.vercel.app`).catch(() => {});
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex min-h-screen bg-[rgb(var(--bg))]">
      <AppNav />
      <main className="flex-1 md:ml-60 pt-14 md:pt-0 px-4 md:px-8 py-6 pb-24 md:pb-10">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
            <div>
              <h1 className="text-2xl font-bold text-[rgb(var(--fg))] flex items-center gap-2">
                <FileText size={22} className="text-violet-400" /> Research CV
              </h1>
              <p className="text-sm text-[rgb(var(--muted))] mt-1">Auto-generated from your GapForge activity.</p>
            </div>
            {cvData && (
              <div className="flex gap-2">
                <button onClick={copyText} className="flex items-center gap-2 px-3 py-2 rounded-xl border border-[rgb(var(--border))] text-sm text-[rgb(var(--muted))] hover:text-[rgb(var(--fg))] transition-colors">
                  {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />} Copy
                </button>
                <button onClick={exportMarkdown} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium transition-colors">
                  <Download size={14} /> Export CV
                </button>
              </div>
            )}
          </div>

          {loading ? (
            <div className="flex items-center justify-center py-20"><Loader2 size={24} className="animate-spin text-violet-400" /></div>
          ) : !cvData ? null : (
            <div className="space-y-5">
              {/* Profile card */}
              <div className="card p-6 bg-gradient-to-br from-violet-600/5 to-violet-800/5 border-violet-500/20">
                <div className="flex items-start gap-4">
                  {session?.user?.image ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={session.user.image} alt={cvData.name} className="w-16 h-16 rounded-2xl object-cover flex-shrink-0 ring-2 ring-violet-500/20" />
                  ) : (
                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-violet-500 to-violet-700 flex items-center justify-center flex-shrink-0">
                      <span className="text-2xl font-black text-white">{cvData.name[0]}</span>
                    </div>
                  )}
                  <div className="flex-1">
                    <h2 className="text-xl font-bold text-[rgb(var(--fg))]">{cvData.name}</h2>
                    {cvData.institution && <p className="text-sm text-[rgb(var(--muted))] flex items-center gap-1.5 mt-0.5"><Building2 size={12} /> {cvData.institution}</p>}
                    {cvData.careerStage && <p className="text-xs text-violet-400 mt-1 capitalize">{cvData.careerStage.replace("-", " ")}</p>}
                    {cvData.bio && <p className="text-sm text-[rgb(var(--muted))] mt-2 leading-relaxed">{cvData.bio}</p>}
                    {cvData.researchAreas.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mt-3">
                        {cvData.researchAreas.slice(0, 6).map(a => (
                          <span key={a} className="text-xs px-2 py-0.5 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20">{a}</span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { icon: Zap, label: "Gaps found", value: cvData.stats.gapsFound, color: "text-violet-400 bg-violet-400/10" },
                  { icon: BookOpen, label: "Searches run", value: cvData.stats.searchesRun, color: "text-blue-400 bg-blue-400/10" },
                  { icon: Flame, label: "Day streak", value: cvData.stats.streak, color: "text-orange-400 bg-orange-400/10" },
                  { icon: Star, label: "Papers saved", value: cvData.stats.papersSaved, color: "text-amber-400 bg-amber-400/10" },
                ].map(({ icon: Icon, label, value, color }) => (
                  <div key={label} className="card p-4 text-center">
                    <div className={cn("w-10 h-10 rounded-xl flex items-center justify-center mx-auto mb-2", color)}>
                      <Icon size={18} />
                    </div>
                    <p className="text-2xl font-black text-[rgb(var(--fg))]">{value}</p>
                    <p className="text-xs text-[rgb(var(--muted))] mt-0.5">{label}</p>
                  </div>
                ))}
              </div>

              {/* Recent gaps */}
              {cvData.recentGaps.length > 0 && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-[rgb(var(--fg))] mb-3 flex items-center gap-2">
                    <Zap size={14} className="text-violet-400" /> Recently discovered gaps
                  </h3>
                  <div className="space-y-2">
                    {cvData.recentGaps.map((gap, i) => (
                      <div key={i} className="flex items-start gap-3 py-2 border-b border-[rgb(var(--border))] last:border-0">
                        <span className="text-xs font-bold text-violet-400 w-5">{i + 1}.</span>
                        <div className="flex-1">
                          <p className="text-sm text-[rgb(var(--fg))]">{gap.title}</p>
                          <p className="text-xs text-[rgb(var(--muted))] mt-0.5 capitalize">{gap.category.replace(/-/g, " ")} · {new Date(gap.created_at).toLocaleDateString()}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Badges */}
              {cvData.badges.length > 0 && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-[rgb(var(--fg))] mb-3 flex items-center gap-2">
                    <Trophy size={14} className="text-amber-400" /> Achievements
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {cvData.badges.map(b => (
                      <span key={b.badge_type} className="text-xs px-3 py-1.5 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 font-medium">
                        {BADGE_LABELS[b.badge_type] ?? b.badge_type}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <div className="text-center text-xs text-[rgb(var(--muted))] py-2">
                Generated by GapForge · <a href="https://gapforge-self.vercel.app" className="text-violet-400">gapforge-self.vercel.app</a>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
