/**
 * PDF Export Utility — browser-based, no dependencies
 * Uses the browser's print functionality with a clean print stylesheet
 */

export interface PdfExportOptions {
  title: string;
  content: string; // markdown or plain text
  filename?: string;
  subtitle?: string;
  footer?: string;
}

// Convert markdown to clean HTML for printing
function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^#### (.+)$/gm, "<h4>$1</h4>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/__([^_]+)__/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/_([^_]+)_/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^[-*•]\s+(.+)$/gm, "<li>$1</li>")
    .replace(/^(\d+)\.\s+(.+)$/gm, "<li>$2</li>")
    .replace(/^---+$/gm, "<hr>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");
}

export function exportToPdf(options: PdfExportOptions): void {
  const { title, content, filename, subtitle, footer } = options;
  const html = markdownToHtml(content);

  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 11pt;
      line-height: 1.7;
      color: #1a1a2e;
      background: white;
      padding: 2.5cm;
      max-width: 21cm;
      margin: 0 auto;
    }
    .header {
      border-bottom: 2px solid #7c3aed;
      padding-bottom: 1cm;
      margin-bottom: 1cm;
    }
    .header h1 {
      font-size: 20pt;
      color: #1a1a2e;
      margin-bottom: 4px;
    }
    .header .subtitle {
      font-size: 10pt;
      color: #666;
    }
    .header .meta {
      font-size: 9pt;
      color: #999;
      margin-top: 4px;
    }
    .brand {
      font-size: 9pt;
      color: #7c3aed;
      font-weight: bold;
      float: right;
      margin-top: 4px;
    }
    h1 { font-size: 16pt; margin: 20px 0 8px; color: #1a1a2e; }
    h2 { font-size: 13pt; margin: 18px 0 6px; color: #1a1a2e; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    h3 { font-size: 11pt; margin: 14px 0 4px; color: #374151; }
    h4 { font-size: 11pt; margin: 12px 0 4px; color: #7c3aed; font-style: italic; }
    p { margin: 8px 0; }
    ul, ol { margin: 8px 0 8px 20px; }
    li { margin: 4px 0; }
    strong { font-weight: bold; }
    em { font-style: italic; }
    code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-family: monospace; font-size: 9pt; }
    pre { background: #f9fafb; border: 1px solid #e5e7eb; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 9pt; margin: 12px 0; }
    blockquote { border-left: 3px solid #7c3aed; padding-left: 12px; margin: 12px 0; color: #6b7280; font-style: italic; }
    hr { border: none; border-top: 1px solid #e5e7eb; margin: 16px 0; }
    .footer {
      margin-top: 2cm;
      padding-top: 0.5cm;
      border-top: 1px solid #e5e7eb;
      font-size: 8pt;
      color: #9ca3af;
      text-align: center;
    }
    @media print {
      body { padding: 0; }
      @page { margin: 2cm; size: A4; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">GapForge</div>
    <h1>${title}</h1>
    ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ""}
    <div class="meta">Generated on ${new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" })} · gapforge.app</div>
  </div>
  <div class="content">
    <p>${html}</p>
  </div>
  ${footer ? `<div class="footer">${footer}</div>` : '<div class="footer">Generated by GapForge · gapforge.app · Research Intelligence Platform</div>'}
  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
        window.onafterprint = function() { window.close(); };
      }, 500);
    };
  </script>
</body>
</html>
  `);

  printWindow.document.close();
}

// Export as plain text file
export function exportAsText(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${filename}.txt`; a.click();
  URL.revokeObjectURL(url);
}

// Export as markdown file
export function exportAsMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${filename}.md`; a.click();
  URL.revokeObjectURL(url);
}
