import { PublicNav } from "@/components/nav";

export default function TermsPage() {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: "By accessing or using GapForge, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform."
    },
    {
      title: "2. Description of Service",
      content: "GapForge is a research intelligence platform that uses AI to identify candidate research gaps from academic literature. Results are for informational purposes and represent candidate gaps for the researcher's own evaluation — not guaranteed findings."
    },
    {
      title: "3. User Accounts",
      content: "You must sign in via Google or GitHub to access personalized features. You are responsible for maintaining the confidentiality of your account. You agree to provide accurate information and to notify us immediately of any unauthorized use."
    },
    {
      title: "4. Acceptable Use",
      content: "You agree not to: use GapForge for any unlawful purpose; attempt to gain unauthorized access to any part of the platform; use automated scripts to abuse the search functionality; resell or redistribute GapForge outputs without attribution; or attempt to reverse-engineer the platform."
    },
    {
      title: "5. Intellectual Property",
      content: "The GapForge platform, including its design, code, and branding, is owned by GapForge. Research content from academic sources retains its original copyright. Gap analysis outputs generated by GapForge are provided for your personal research use."
    },
    {
      title: "6. Disclaimers",
      content: "GapForge is provided 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or fitness for purpose of gap detection results. Academic citations are sourced from third-party databases and should be independently verified."
    },
    {
      title: "7. Limitation of Liability",
      content: "To the fullest extent permitted by law, GapForge shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid in the 12 months preceding the claim."
    },
    {
      title: "8. Changes to Terms",
      content: "We may update these Terms at any time. Continued use of GapForge after changes constitutes acceptance of the updated Terms. We will notify users of material changes via email."
    },
    {
      title: "9. Contact",
      content: "For questions about these Terms, contact us at gahedmund146@gmail.com."
    },
  ];

  return (
    <div className="min-h-screen bg-[rgb(var(--bg))]">
      <PublicNav />
      <div className="max-w-3xl mx-auto px-4 pt-24 pb-24 md:pb-10">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-[rgb(var(--fg))]">Terms of Service</h1>
          <p className="text-sm text-[rgb(var(--muted))] mt-2">Effective date: August 5, 2026</p>
        </div>
        <div className="space-y-4">
          {sections.map((s) => (
            <div key={s.title} className="card p-6">
              <h2 className="font-semibold text-[rgb(var(--fg))] mb-2">{s.title}</h2>
              <p className="text-sm text-[rgb(var(--muted))] leading-relaxed">{s.content}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
