"use client";

import { useState } from "react";
import { AppNav } from "@/components/nav";
import { motion } from "framer-motion";
import {
  ShieldCheck, Loader2, Copy, Check, Download,
  AlertCircle, CheckCircle2, Star, RefreshCw, FileText,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { MarkdownContent } from "@/components/markdown-content";

interface ReviewScore {
  label: string;
  score: number; // 1-10
  comment: string;
}

interface PeerReview {
  overallScore: number;
  verdict: "accept" | "minor_revision" | "major_revision" | "reject";
  summary: string;
  scores: ReviewScore[];
  strengths: string[];
  weaknesses: string[];
  specificComments: string;
  suggestedRevisions: string[];
  recommendedJournals: string[];
}

const VERDICT_CONFIG = {
  accept: { label: "Accept", color: "text-green-400 bg-green-400/10 border-green-400/30", icon: CheckCircle2 },
  minor_revision: { label: "Minor Revision", color: "text-blue-400 bg-blue-400/10 border-blue-400/30", icon: CheckCircle2 },
  major_revision: { label: "Major Revision", color: "text-amber-400 bg-amber-400/10 border-amber-400/30", icon: AlertCircle },
  reject: { label: "Reject", color: "text-red-400 bg-red-400/10 border-red-400/30", icon: AlertCircle },
};

function ScoreBar({ label, score, comment }: ReviewScore) {
  const color = score >= 8 ? "bg-green-500" : score >= 6 ? "bg-blue-500" : score >= 4 ? "bg-amber-500" : "bg-red-500";
  return (
    <div className="space-y-1">
      <div className="flex items-center justify-between">
        <span className="text-sm text-[rgb(var(--fg))]">{label}</span>
        <span className="text-sm font-bold text-[rgb(var(--fg))]">{score}/10</span>
      </div>
      <div className="h-2 bg-[rgb(var(--border))] rounded-full overflow-hidden">
        <div className={cn("h-full rounded-full transition-all duration-700", color)} style={{ width: `${score * 10}%` }} />
      </div>
      <p className="text-xs text-[rgb(var(--muted))]">{comment}</p>
    </div>
  );
}

export default function PeerReviewPage() {
  const [title, setTitle] = useState("");
  const [abstract, setAbstract] = useState("");
  const [field, setField] = useState("");
  const [targetJournal, setTargetJournal] = useState("");
  const [loading, setLoading] = useState(false);
  const [review, setReview] = useState<PeerReview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    if (!abstract.trim()) return;
    setLoading(true); setError(null); setReview(null);
    try {
      const res = await fetch("/api/peer-review", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, abstract, field, targetJournal }),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error ?? "Failed");
      setReview(d.review);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate review");
    } finally { setLoading(false); }
  };

  const copyReview = () => {
    if (!review) return;
    const text = `PEER REVIEW — ${title || "Untitled Paper"}

VERDICT: ${VERDICT_CONFIG[review.verdict].label}
OVERALL SCORE: ${review.overallScore}/10

SUMMARY:
${review.summary}

SCORES:
${review.scores.map(s => `${s.label}: ${s.score}/10 — ${s.comment}`).join("\n")}

STRENGTHS:
${review.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

WEAKNESSES:
${review.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n")}

SPECIFIC COMMENTS:
${review.specificComments}

SUGGESTED REVISIONS:
${review.suggestedRevisions.map((r, i) => `${i + 1}. ${r}`).join("\n")}

Generated by GapForge AI Peer Review`;
    navigator.clipboard.writeText(text).catch(() => {});
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex min-h-screen bg-[rgb(var(--bg))]">
      <AppNav />
      <main className="flex-1 md:ml-60 pt-14 md:pt-0 px-4 md:px-8 py-6 pb-24 md:pb-10">
        <div className="max-w-4xl mx-auto">
          <div className="mb-6">
            <h1 className="text-2xl font-bold text-[rgb(var(--fg))] flex items-center gap-2">
              <ShieldCheck size={22} className="text-violet-400" /> AI Peer Review Simulator
            </h1>
            <p className="text-sm text-[rgb(var(--muted))] mt-1">
              Get simulated peer review feedback before submitting. Scores, critique, and revision suggestions.
            </p>
          </div>

          {!review ? (
            <div className="card p-6 space-y-4">
              <div>
                <label className="text-xs text-[rgb(var(--muted))] mb-1.5 block">Paper title <span className="opacity-60">(optional)</span></label>
                <input value={title} onChange={e => setTitle(e.target.value)}
                  placeholder="Your paper title"
                  className="w-full px-3 py-2.5 rounded-xl bg-[rgb(var(--bg))] border border-[rgb(var(--border))] text-sm text-[rgb(var(--fg))] placeholder:text-[rgb(var(--muted))] outline-none focus:border-violet-500" />
              </div>
              <div>
                <label className="text-xs text-[rgb(var(--muted))] mb-1.5 block">Abstract or full paper text <span className="text-red-400">*</span></label>
                <textarea value={abstract} onChange={e => setAbstract(e.target.value)} rows={8}
                  placeholder="Paste your abstract or full paper text here. The more you provide, the more detailed the review."
                  className="w-full px-3 py-2.5 rounded-xl bg-[rgb(var(--bg))] border border-[rgb(var(--border))] text-sm text-[rgb(var(--fg))] placeholder:text-[rgb(var(--muted))] outline-none focus:border-violet-500 resize-none" />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-[rgb(var(--muted))] mb-1.5 block">Research field</label>
                  <input value={field} onChange={e => setField(e.target.value)}
                    placeholder="e.g. Neuroscience, ML, Climate"
                    className="w-full px-3 py-2.5 rounded-xl bg-[rgb(var(--bg))] border border-[rgb(var(--border))] text-sm text-[rgb(var(--fg))] placeholder:text-[rgb(var(--muted))] outline-none focus:border-violet-500" />
                </div>
                <div>
                  <label className="text-xs text-[rgb(var(--muted))] mb-1.5 block">Target journal <span className="opacity-60">(optional)</span></label>
                  <input value={targetJournal} onChange={e => setTargetJournal(e.target.value)}
                    placeholder="e.g. Nature, JAMA, NeurIPS"
                    className="w-full px-3 py-2.5 rounded-xl bg-[rgb(var(--bg))] border border-[rgb(var(--border))] text-sm text-[rgb(var(--fg))] placeholder:text-[rgb(var(--muted))] outline-none focus:border-violet-500" />
                </div>
              </div>
              {error && <p className="text-sm text-red-400">{error}</p>}
              <button onClick={generate} disabled={loading || !abstract.trim()}
                className="w-full py-3 rounded-xl bg-violet-600 hover:bg-violet-700 disabled:opacity-40 text-white font-semibold flex items-center justify-center gap-2 transition-colors">
                {loading ? <><Loader2 size={16} className="animate-spin" /> Reviewing your paper...</> : <><ShieldCheck size={16} /> Generate peer review</>}
              </button>
              <p className="text-xs text-center text-[rgb(var(--muted))]">
                Simulated review by AI trained on academic standards. Not a replacement for real peer review.
              </p>
            </div>
          ) : (
            <div className="space-y-5">
              {/* Header actions */}
              <div className="flex items-center justify-between flex-wrap gap-3">
                <h2 className="text-sm font-semibold text-[rgb(var(--fg))]">
                  Review for: {title || "Your paper"}
                </h2>
                <div className="flex gap-2">
                  <button onClick={() => setReview(null)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[rgb(var(--border))] text-xs text-[rgb(var(--muted))] hover:text-[rgb(var(--fg))] transition-colors">
                    <RefreshCw size={12} /> New review
                  </button>
                  <button onClick={copyReview}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[rgb(var(--border))] text-xs text-[rgb(var(--muted))] hover:text-[rgb(var(--fg))] transition-colors">
                    {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
                    {copied ? "Copied" : "Copy report"}
                  </button>
                </div>
              </div>

              {/* Verdict + overall score */}
              <div className="card p-6">
                <div className="flex items-center justify-between flex-wrap gap-4">
                  <div>
                    {(() => {
                      const cfg = VERDICT_CONFIG[review.verdict];
                      const Icon = cfg.icon;
                      return (
                        <div className={cn("inline-flex items-center gap-2 px-4 py-2 rounded-xl border text-sm font-bold", cfg.color)}>
                          <Icon size={15} /> {cfg.label}
                        </div>
                      );
                    })()}
                    <p className="text-xs text-[rgb(var(--muted))] mt-2">
                      {targetJournal ? `Review calibrated for ${targetJournal}` : "General academic review"}
                    </p>
                  </div>
                  <div className="text-center">
                    <div className="text-5xl font-black text-violet-400">{review.overallScore}</div>
                    <div className="text-xs text-[rgb(var(--muted))]">out of 10</div>
                  </div>
                </div>
                <p className="text-sm text-[rgb(var(--muted))] mt-4 leading-relaxed">{review.summary}</p>
              </div>

              {/* Score breakdown */}
              <div className="card p-6 space-y-4">
                <h3 className="text-sm font-semibold text-[rgb(var(--fg))]">Score breakdown</h3>
                {review.scores.map((s, i) => <ScoreBar key={i} {...s} />)}
              </div>

              {/* Strengths + Weaknesses */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-green-400 mb-3 flex items-center gap-2">
                    <CheckCircle2 size={14} /> Strengths
                  </h3>
                  <ul className="space-y-2">
                    {review.strengths.map((s, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-[rgb(var(--muted))]">
                        <span className="text-green-400 font-bold flex-shrink-0 text-xs mt-0.5">{i + 1}.</span>
                        <span>{s}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-amber-400 mb-3 flex items-center gap-2">
                    <AlertCircle size={14} /> Weaknesses
                  </h3>
                  <ul className="space-y-2">
                    {review.weaknesses.map((w, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-[rgb(var(--muted))]">
                        <span className="text-amber-400 font-bold flex-shrink-0 text-xs mt-0.5">{i + 1}.</span>
                        <span>{w}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Specific comments */}
              <div className="card p-5">
                <h3 className="text-sm font-semibold text-[rgb(var(--fg))] mb-3">Detailed reviewer comments</h3>
                <MarkdownContent content={review.specificComments} />
              </div>

              {/* Suggested revisions */}
              <div className="card p-5">
                <h3 className="text-sm font-semibold text-violet-400 mb-3">Suggested revisions</h3>
                <ol className="space-y-2">
                  {review.suggestedRevisions.map((r, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-[rgb(var(--muted))]">
                      <span className="text-violet-400 font-bold flex-shrink-0 w-5">{i + 1}.</span>
                      <span>{r}</span>
                    </li>
                  ))}
                </ol>
              </div>

              {/* Recommended journals */}
              {review.recommendedJournals.length > 0 && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-[rgb(var(--fg))] mb-3">Recommended journals / venues</h3>
                  <div className="flex flex-wrap gap-2">
                    {review.recommendedJournals.map((j, i) => (
                      <span key={i} className="text-xs px-3 py-1.5 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20">{j}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
